// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiBid.Microservices.Auction.Persistence;

#nullable disable

namespace OptiBid.Microservices.Auction.Persistence.Migrations
{
    [DbContext(typeof(AuctionContext))]
    partial class AuctionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Started")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AuctionAssets", (string)null);

                    b.HasDiscriminator<string>("AssetType").HasValue("AuctionAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AuctionAssetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BidDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AuctionAssetId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOpened")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.MediaUrl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AuctionAssetId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AuctionAssetId");

                    b.ToTable("MediaUrl");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Product", b =>
                {
                    b.HasBaseType("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset");

                    b.Property<int?>("ProductCategoryID")
                        .HasColumnType("integer");

                    b.HasIndex("ProductCategoryID");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Service", b =>
                {
                    b.HasBaseType("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset");

                    b.Property<int?>("ServiceCategoryID")
                        .HasColumnType("integer");

                    b.HasIndex("ServiceCategoryID");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset", "Asset")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptiBid.Microservices.Auction.Domain.Entities.Customer", "Customer")
                        .WithMany("Bids")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.MediaUrl", b =>
                {
                    b.HasOne("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset", null)
                        .WithMany("MediaUrls")
                        .HasForeignKey("AuctionAssetId");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Product", b =>
                {
                    b.HasOne("OptiBid.Microservices.Auction.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryID");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Service", b =>
                {
                    b.HasOne("OptiBid.Microservices.Auction.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryID");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.AuctionAsset", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("MediaUrls");
                });

            modelBuilder.Entity("OptiBid.Microservices.Auction.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
